### ISSUE TITLE
Drawing Bugs in the Converter

### ISSUE THREAD

**Issue by Eyantra698Sumanto** [thesourcerer8/xschem2kicad#2]
1. Some components are broken/disconnected/incomplete drawings 
![image](https://user-images.githubusercontent.com/58599984/163925469-b603d0dc-721c-4744-b38c-e62affd34a04.png)
![image](https://user-images.githubusercontent.com/58599984/163925531-7f0a4dd0-6798-416f-9484-1e01d3fcb8c9.png)

2. Instead of Ports boxes are displayed(I am trying to replace but again coordinates issue). The Boxes('B') in Xschem need to be replaced by Ports('X') in KiCAD.
In the following figure the marks boxes need to be replaced by ports:
![image](https://user-images.githubusercontent.com/58599984/163925616-97e69c51-2f93-4ab6-bec3-0f619578f3cb.png)
3. Many components are simply boxes. For example:
![image](https://user-images.githubusercontent.com/58599984/163925839-66dea8d6-ab90-453b-bbf1-4e682ece3914.png)

**Comment by thesourcerer8** [comment]
I have fixed the issues now. Except for the last one, the test_mim_cap symbol looks exactly like that in xschem, so it works as designed.
